name: PHP Composer

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: composer install